name: Clean Workflow Logs

on:
  schedule:
    - cron: 0 0/2 * * *
  workflow_dispatch:
    inputs:
      days_old:
        description: "The amount of days old to delete"
        default: "1"
        required: false

permissions:
  actions: write

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          days_old: 0
          # days_old: ${{ github.event.inputs.days_old }}
