name: docker publish
on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo -n ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin
          docker build -t ghcr.io/popcube/x_update_gt:1.0 .
          docker push ghcr.io/popcube/x_update_gt:1.0