name: main
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: |
          pip install --upgrade pip --quiet
          pip install boto3 --quiet
          pip install requests --quiet
      - run: python ./main.py
          
          
