name: main
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_LAM_ACC_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_LAM_SEC_ACC_KEY }}
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - uses: actions/checkout@v4
      - run: |
          pip install --upgrade pip --quiet
          pip install boto3 --quiet
          pip install requests --quiet
      - run: python ./main.py
          
          
