name: sub
on: 
  workflow_dispatch:
  # schedule:
  #   - cron: '0/5 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_LAM_ACC_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_LAM_SEC_ACC_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - uses: actions/checkout@v4
      - run: |
          pip install boto3
          pip install requests
      - run: python ./main.py
          
          
