on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.FULL_REPO_TOKEN }} > ./out.txt
      - uses: actions/upload-artifact@v4
        with:
          path: ./out.txt